### PR TITLE
Added autoCloseDay and autoCloseTime options 

### PR DESCRIPTION
**Pull request by MitMaro**
Added autoCloseDay and autoCloseTime options that will close Rome only day or time change respectively.

If there are any changes that can be made I will gladly update.

### CODE REVIEW

**Comment by bevacqua** [comment]
Rather than adding more options, I was hoping to add more values for the `autoClose` option.

- `true` always auto-closes
- `false` never auto-closes
- `day` auto-closes when day is picked
- `time` auto-closes when time is picked

**Comment by MitMaro** [comment]
Would setting to true also make it always close when time is selected, even if there is a day picker. Currently it only closes on time when there is no day picker.

**Comment by bevacqua** [comment]
Leave `true` and `false` behavior as-is

**Comment by MitMaro** [comment]
Updated.

**Comment by bevacqua** [comment]
Let's remove the `'day'` option _(it's actually the same as `true`)_. You can reword the documentation as:

> When set to `true`, the calendar is closed when picking a day _(or a time if `time: true` and `date: false`)_ . A value of `time` will only close the calendar when a time is picked.

**Comment by MitMaro** [comment]
I didn't like that duplication myself. Updated.

**Comment by bevacqua** [comment]
Thank you. Released as `2.1.0`

**Comment by MitMaro** [comment]
Thanks!

**Pull request merged**
