### PR TITLE
Strict parse

### PR DESCRIPTION
**Pull request by valotas**
Introduced `strictParse` option.

When true makes a strict parsing of the given input value. This should fix the problem discussed with #64

### CODE REVIEW

**Comment by bevacqua** [comment]
Remove the example from the HTML as it adds little value, then squash your commits and I'll merge this.

**Comment by valotas** [comment]
Sure, I'll try to do that tomorrow morning!

**Comment by valotas** [comment]
There you go!

I did not  squash the fist commit as it did not have anything to do with the issue.

**Comment by bevacqua** [comment]
Thank you. Released as `2.0.4`

**Pull request merged**
