### PR TITLE
Added "allowUserInput" option

### PR DESCRIPTION
**Pull request by romankras**
Added option that allows to enter manually date and time which are not
present in the dropdown

### CODE REVIEW

**Comment by bevacqua** [comment]
Why not use a `dateValidator` that always returns `true` instead?

**Comment by romankras** [comment]
If i understand correctly, in this case every input would be valid. I wanted to save validation against date and time foramts provided in the config dictionary.

**Comment by bevacqua** [comment]
```js
dateValidator: function (date) {
  return valid.indexOf(date) !== -1
}
```

**Comment by romankras** [comment]
Sorry, but this snippet throwing the following error:
`Uncaught ReferenceError: valid is not defined`
Should I change something else?

**Comment by bevacqua** [comment]
Yes, your "config dictionary"

**Pull request closed without merging**
