### PR TITLE
Stop 'hide' event from firing when calendar is already hidden

### PR DESCRIPTION
**Pull request by codekipple**
Added check to hideCalendar() function to avoid calling the hide event when the calendar was already hidden.

Without this the hide event is called every time the user clicks the mouse.

### CODE REVIEW

**Comment by codekipple** [comment]
See issue #91

**Comment by bevacqua** [comment]
Cool. Additionally we should probably move to using CSS classes rather than hardcoded styles.

**Comment by codekipple** [comment]
Yes that would be a good idea. Toggling a class both on the datepicker and the associated element.

**Comment by bevacqua** [comment]
Want to create a PR for that too? Just needs to move the styles to the stylus file and use class names instead of inline styles

**Comment by codekipple** [comment]
Ok I'll have a look at it. I'm going to give 'free navigation' a go first, you mention here #105 as that's the thing I need at the moment on the website I'm building.

**Comment by bevacqua** [comment]
Sweet. Thanks for putting work in for `rome` :)

**Comment by codekipple** [comment]
Would you be interested in a pull request adding watchify to the gulp setup? I've just added it for myself to speed up builds when working.

It makes a big difference making a change on watch of the js builds in about 0.15 seconds as opposed to 5 seconds. Also the gulp file might benefit from sectioning up a bit with comments.

**Comment by bevacqua** [comment]
Sure.

**Pull request merged**
