### PR TITLE
Add ability to change weekdays format.

### PR DESCRIPTION
**Pull request by deini**
Right now there is no way to change the weekdays format AFAIK. :dancer:

### CODE REVIEW

**Comment by deini** [comment]
@bevacqua Thanks for the feedback, what about something like this? 16e62b8

**Comment by bevacqua** [comment]
Rename the option to weekdayFormat, squash, and I'll merge. Thanks!

**Comment by deini** [comment]
Done :dancer: @bevacqua

**Comment by bevacqua** [comment]
Great. Released as `1.2.2`.

**Pull request merged**
